# Generated by Django 4.1.2 on 2022-12-02 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='element',
            name='type',
            field=models.CharField(choices=[('Video', 'Video'), ('Document', 'Document'), ('Tool', 'Tool'), ('Intranet Link', 'Intranet Link')], max_length=50),
        ),
    ]
